"""initial_schema

Revision ID: 8dbc81475c5a
Revises: 
Create Date: 2026-06-14 01:39:00.728774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbc81475c5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_masters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('price_unit', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ingredient_masters_id'), 'ingredient_masters', ['id'], unique=False)
    op.create_table('monthly_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('rent', sa.Float(), nullable=True),
    sa.Column('labor', sa.Float(), nullable=True),
    sa.Column('utilities', sa.Float(), nullable=True),
    sa.Column('supplies', sa.Float(), nullable=True),
    sa.Column('other', sa.Float(), nullable=True),
    sa.Column('production_kg', sa.Float(), nullable=False),
    sa.Column('target_profit_rate', sa.Float(), nullable=True),
    sa.Column('takeout_packaging', sa.Float(), nullable=True),
    sa.Column('takeout_unit_weight', sa.Float(), nullable=True),
    sa.Column('eatin_multiplier', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_costs_id'), 'monthly_costs', ['id'], unique=False)
    op.create_table('recipe_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('default_customer_tier', sa.String(), nullable=True),
    sa.Column('default_gross_margin', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_recipe_templates_id'), 'recipe_templates', ['id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('raw_weight', sa.Float(), nullable=False),
    sa.Column('raw_price', sa.Float(), nullable=False),
    sa.Column('finished_weight', sa.Float(), nullable=False),
    sa.Column('customer_tier', sa.String(), nullable=False),
    sa.Column('yield_rate', sa.Float(), nullable=False),
    sa.Column('cost_per_kg', sa.Float(), nullable=False),
    sa.Column('recommended_price', sa.Float(), nullable=False),
    sa.Column('gross_margin', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_table('whole_pigs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('carcass_weight', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whole_pigs_id'), 'whole_pigs', ['id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('finished_weight', sa.Float(), nullable=False),
    sa.Column('customer_tier', sa.String(), nullable=False),
    sa.Column('custom_rate', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_kg', sa.Float(), nullable=False),
    sa.Column('recommended_price', sa.Float(), nullable=False),
    sa.Column('gross_margin', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('waste_weight', sa.Float(), nullable=True),
    sa.Column('raw_weight', sa.Float(), nullable=True),
    sa.Column('portion_weight', sa.Float(), nullable=True),
    sa.Column('portion_unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['recipe_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_table('cuts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pig_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('raw_weight', sa.Float(), nullable=False),
    sa.Column('finished_weight', sa.Float(), nullable=False),
    sa.Column('customer_tier', sa.String(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_kg', sa.Float(), nullable=False),
    sa.Column('recommended_price', sa.Float(), nullable=False),
    sa.Column('yield_rate', sa.Float(), nullable=False),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('custom_gross_margin', sa.Float(), nullable=True),
    sa.Column('target_revenue', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pig_id'], ['whole_pigs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuts_id'), 'cuts', ['id'], unique=False)
    op.create_table('template_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['recipe_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_ingredients_id'), 'template_ingredients', ['id'], unique=False)
    op.create_table('batch_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('price_per', sa.Float(), server_default='1', nullable=False),
    sa.Column('price_unit', sa.String(), server_default='kg', nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_ingredients_id'), 'batch_ingredients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_ingredients_id'), table_name='batch_ingredients')
    op.drop_table('batch_ingredients')
    op.drop_index(op.f('ix_template_ingredients_id'), table_name='template_ingredients')
    op.drop_table('template_ingredients')
    op.drop_index(op.f('ix_cuts_id'), table_name='cuts')
    op.drop_table('cuts')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_whole_pigs_id'), table_name='whole_pigs')
    op.drop_table('whole_pigs')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_recipe_templates_id'), table_name='recipe_templates')
    op.drop_table('recipe_templates')
    op.drop_index(op.f('ix_monthly_costs_id'), table_name='monthly_costs')
    op.drop_table('monthly_costs')
    op.drop_index(op.f('ix_ingredient_masters_id'), table_name='ingredient_masters')
    op.drop_table('ingredient_masters')
    # ### end Alembic commands ###
